### ISSUE TITLE
Works in neovim?

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#12]
I'm lurking in here too :smile: 

I installed vim-niffler in neovim with vim-plug but when I go into one of my projects and run `:Niffler` it seems to open but nothing happends when I write into the window.

My neovim version info:

```
NVIM 0.0.0-alpha+201504060149 (compiled Apr  6 2015 10:58:42)
Commit: 0af7c8f62412d6e3ceb6f10169ef5ea3b70868e5
```

**Comment by pgdouyon** [comment]
Hmm it should work in Neovim, I've been successfully using Niffler in Neovim for about 4 months now.  After you type the `:Niffler` command is there a list of files displayed or is it simply that no filtering occurs when you begin typing.

Someone actually mentioned a similar problem with Unite.vim today in Neovim's Gitter channel.  But they eventually determined that it was another plugin (https://github.com/osyo-manga/vim-brightest/) that prevented them from typing in Unite.vim's window.  Can you try running the `:Niffler` command with the same minimal vimrc from the other issue, only loading the Niffler plugin and no other plugins/settings and let me know if the problem still occurs?

**Comment by marlun** [comment]
I created a asciinema recording: https://asciinema.org/a/18633 I'm sorry if it's a little slow, first time I ever did one.

When doing that the only plugin I had installed (with vim-plug) is vim-niffler:

``` vim
call plug#begin('~/.nvim/bundle')
Plug 'pgdouyon/vim-niffler'
call plug#end()
```

**Comment by pgdouyon** [comment]
Sorry about that, I completely forgot to test the default behavior of the `g:niffler_ignore_dirs` and `g:niffler_ignore_extensions` options.  I just pushed a commit that should fix the problem for you.  Can you update to the latest and let me know if you still see it?

Also, just so you know, by default `:Niffler` with no arguments, actually fetches all the files under the $HOME directory instead of the current working directory.  I realize now that this behavior is kind of insane, but I originally did it because I don't change my working directory in Vim often and I wanted quick access to all of my files.  Let me know if it's a problem and I can push a fix for that too.

**Comment by marlun** [comment]
Works now, thanks!

I've been using FuzzyFinder for a long time trying ctrlp, unite and others but always going back to FuzzyFinder because it has such an easy UI and does what I want. FuzzyFinder do have some performance problems however (which won't be fixed since it's no longer maintained) so I've been searching for something new. Niffler looks really nice and I'll try it out :+1:
