### ISSUE TITLE
Learn which files I use the most and sort them higher

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#13]
In a lot of my projects I use some files a lot more than others and one thing that I appreciated a lot with FuzzyFinder was that it learned which files I used a lot and sorted them higher on the list (if they matched) preventing me from having to move the selected item most of the times.

**Comment by pgdouyon** [comment]
Does the NifflerMRU command not do this for you?  Granted the most recently accessed file is actually at the bottom of the list in this case, but that should be fine since the cursor also starts at the bottom of the list.

I actually haven't added any sorting to Niffler yet, besides the NifflerMRU command.  Partially because sorting a large file list would cause a big drop in performance without dropping down to a language with a faster runtime than VimL, and also partially because I've found that matching for the exact text by default is usually fast/accurate enough that I don't need sorting.

**Edit**
I keep forgetting that Niffler doesn't actually deal with the whole file list at once, just what can fit on the screen.  This might actually be feasible to implement sorting compared against Niffler's internal MRU list.  This would still be pretty complicated though so I won't be able to take a look at if it's possible until at least this weekend.

**Comment by marlun** [comment]
One of the things I like about Niffler is that the code is clean and simple to understand, wouldn't want that to change but if we could somehow sort it against the MRU without adding too much complexity that would be great.

**Comment by marlun** [comment]
The reason I want this is because for some reason the file I want is most of the time at the top of the list and the cursor is at the bottom so I always have to write more into the filter than I'd like or move the cursor (if this wasn't clear already :smile:).

**Comment by marlun** [comment]
Have you thought about selecting the first line in the list instead of the last? One reason why I prefer it is that the way you have it right now (the last item is selected), as I enter the filer the result changes and so do the selected line. Your eyes have to move to see which file is selected. If you select the first one your eyes can always stay at the top and it's easier to keep track of the selected item.

**Comment by pgdouyon** [comment]
Niffler originally had the first line selected and then I overhauled the codebase a while back and for some reason moved it to the bottom.  I don't really know why, but I agree it would make more sense to put the cursor at the top.

Also I'm pretty sure I can implement sorting without adding too much complexity to Niffler, it would just be an extra hook in between filtering the results and displaying them on screen.  The sorting function could be complicated, but the MRU list for sorting is already built-in so it shouldn't be too difficult to incorporate.

Thanks for all your suggestions these are great, I'll get to work on them over the next couple of days and I think they'll go a long way towards improving Niffler.

**Comment by marlun** [comment]
Is this all that's needed to move the cursor to the top? Seems to work for me but I've only done some quick testing.

``` diff
diff --git a/plugin/niffler.vim b/plugin/niffler.vim
index b7260ce..4dae620 100644
--- a/plugin/niffler.vim
+++ b/plugin/niffler.vim
@@ -1,3 +1,4 @@
+" vim:et:ts=4:sw=4:sts=4
 "==============================================================================
 "File:        niffler.vim
 "Description: Fuzzy file finder for Vim.  Supported modes are fuzzy file find by
@@ -277,7 +278,7 @@ endfunction


 function! s:keypress_event_loop()
-    call cursor(line("$"), 1)
+    call cursor(1, 1)
     let prompt = ""
     redraw
     echon s:prompt
@@ -298,6 +299,7 @@ function! s:update_prompt(prompt, char)
     let prompt = a:prompt . a:char
     let query = s:parse_query(prompt)
     call s:filter_candidate_list(query)
+    call cursor(1, 1)
     redraw
     echon s:prompt prompt
     return prompt
@@ -309,6 +311,7 @@ function! s:backspace(prompt)
     let query = s:parse_query(prompt)
     let b:niffler_candidate_string = join(b:niffler_candidate_list, "\n")
     call s:filter_candidate_list(query)
+    call cursor(1, 1)
     redraw
     echon s:prompt prompt
     return prompt
@@ -320,6 +323,7 @@ function! s:backward_kill_word(prompt)
     let query = s:parse_query(prompt)
     let b:niffler_candidate_string = join(b:niffler_candidate_list, "\n")
     call s:filter_candidate_list(query)
+    call cursor(1, 1)
     redraw
     echon s:prompt prompt
     return prompt
@@ -330,6 +334,7 @@ function! s:backward_kill_line(prompt)
     let empty_prompt = ""
     let b:niffler_candidate_string = join(b:niffler_candidate_list, "\n")
     call s:filter_candidate_list(empty_prompt)
+    call cursor(1, 1)
     redraw
     echon s:prompt
     return empty_prompt
```

Seem to be some repeating code though:

``` vim
    call cursor(1, 1)
    redraw
    echon s:prompt prompt
```

**Comment by pgdouyon** [comment]
Yup I actually moved the second `call cursor(1, 1)` into the `s:display()` function in my local copy since that function is the one moving the cursor from where it was originally placed.

**Comment by pgdouyon** [comment]
Oh sorry I lied, I forgot you also need to update the `niffler_mru()` function.  Otherwise the list will be in reverse order.  You just have to change the line `call s:niffler_setup(join(s:mru_list, "\n"))` to `call s:niffler_setup(join(reverse(copy(s:mru_list)), "\n"))`

**Comment by marlun** [comment]
Makes sense, thanks :)

**Comment by pgdouyon** [comment]
The latest set of commits should both sort the file list according to the most recently used files and also default to selecting the first line in the list instead of the last.

I didn't run into any bugs while testing it out, but let me know if you run into any problems with this latest version.  Thanks again for all your feedback.

**Comment by marlun** [comment]
Great work, thanks!
