### ISSUE TITLE
Add support for multiple selections

### ISSUE THREAD

**Issue by pgdouyon** [pgdouyon/vim-niffler#28]

**Comment by marlun** [comment]
Just curious, what is the usecases where you use this feature?

**Comment by pgdouyon** [comment]
Opening multiple related files mostly, I don't imagine using it with tags, although it's technically supported.  Sometimes at work I'll have a bunch of files with the same name in them like FooBarI, FooBarHibernate, FooBarFactory, or something like that.  This lets you search for FooBar and select all three of them to open instead of having to invoke Niffler three separate times.

**Comment by marlun** [comment]
Thanks, I've never felt the need for it since I only get one of the files in the current buffer and then have to do :NifflerBuffer (or using some some core vim features) to get to the others and then I feel I can just as well do :Niffler . again :smile: I guess it's more effective to do it your way. Will try to think about it next time I'm working on a file with a corresponding test file FooBar and FooBarTests.

Also, I tried to select two files and then hit ctrl-v thinking it would open up in two buffers split vertically :smiley: (not sure if that's a good idea or not)

**Comment by pgdouyon** [comment]
yea I decided to open the extra marked files in the background, and only the file that the cursor was under will open in the foreground.  That way if you happen to need to open 3 or 4 files at a time the screen is cramped with a bunch of splits/tabs that then need to be closed.  It would have been nice to open them all in the foreground, but doesn't scale well enough.
