### ISSUE TITLE
What is causing my dotfiles not to show up?

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#33]
This might be because of vim and not Niffler but hidden files are not shown in Niffler, is that by design or because of some vim configuration value?

**Comment by pgdouyon** [comment]
No Niffler excludes dotfiles by design since they usually contain a lot of noise that would slow down Niffler considerably and that you wouldn't normally want to search through like .git, .svn, .cache, .gems, etc.  

I thought it was a reasonable tradeoff since there are probably only a handful of dotfiles that people would want to regularly open, and those can be handled by a mapping or just using `:e` with tab completion.

If there's an entire dotfile directory you want to open, such as .config or something, the easiest thing to do would probably be to just make a mapping to `:Niffler ~/.config`

Alternatively, you could also set `g:niffler_user_command` to a value like `ag %s -g "" --hidden`.  Niffler only ignores dotfiles using the default `find` command and won't do any filtering if `g:niffler_user_command` is set.

**Comment by marlun** [comment]
Makes sense. Only reason I started thinking about it is because I've got a lot of .gitignore, .gitattributes, .nvmrc, .eslintrc, etc. at work right now. Will think about using a user command, thanks!
