### ISSUE TITLE
See modified state on files on NifflerBuffer

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#34]
What do you think about getting the modified state of buffers and show it on NifflerBuffer somehow? You should be able to get the + sign from :ls and display is somehow, maybe just a + after the filename `<filename> +`? Or `<filename> (modified)` if we want to be more explicit :)

**Comment by pgdouyon** [comment]
Not sure I understand the use case for this.  

It seems to me that you would only bring up NifflerBuffer when you know you want to switch buffers and which buffer to switch to, at which point you can just check the statusline or tabline for the modified state once you've switched to the desired buffer.

You could use NifflerBuffer to get an overview of the open buffers, but the `:ls` command seems better suited to this and is built-in.  Granted the interface for that command is a little ugly.

Although I think the biggest reason to not add this to Niffler is it would make parsing the buffer name out of the selection more difficult since there might be extra text appended to it that would need to be removed before passing it to the `:buffer` command.  I had to do something similar for NifflerTags and it was extremely painful, a lot of ugly/convoluted sed commands that are hard to understand and maintain.  It would also be somewhat inconsistent since we don't show any file metadata for other commands like Niffler or NifflerMRU.

**Comment by marlun** [comment]
You make a strong case once again :) I agree and will settle on using `:ls`.
