### ISSUE TITLE
Using Niffler in a new empty tab removes/closes tabs

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#35]
I I do `:tabe` to open a new tab and then open niffler and open a file either the old tab is removed and the file is opened in the new tab or the file is opened in the old tab and the new is removed. If I open a new tab and change to the old one and use Niffler to open a file the new empty tab is left alone.

**Comment by pgdouyon** [comment]
hmm I think I see the problem, it's a pretty silly bug due to using `bufname("%")` which returns an empty string when I should be using `bufnr("%")`.  I'll push up a fix for it now.

Not sure if you knew about this feature but you can also open a file in a new tab from within Niffler by pressing `<C-t>` instead of `<CR>` on the file name.

**Comment by marlun** [comment]
I knew about `<C-t>` but in this case I had to run `:tabe` first because I needed to do a `:lcd <path>` before running Niffler to search for and open files in another project directory.

**Comment by pgdouyon** [comment]
Forgot to close it in the commit message but should be fixed in https://github.com/pgdouyon/vim-niffler/commit/365908f0d2ffa35c015ccf2497ddf0dd6ea13240

Thanks for letting me know about the bug, turned out to be pretty nasty actually

**Comment by marlun** [comment]
Works great! Glad I can help and that you fix the problems I find. Niffler is probably the plug-in I use the most (maybe Surround auto-pairs is up there too)
