### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by baghayi** [pgdouyon/vim-niffler#44]
Hi,
It's been a few days I've been using this plugin, it is greate, but also I was having a little bit of problem with case sensitivity.

Regarding this file name "Models\TicketController", if I were to search for it, it would not show in the search list of it type "modelsticketcontroller" or similar, but if I type as is, say "Model..." it shows it in the list.
I looked to config part but could not find anything related to case sensitivit.

Could you please help me on this?

Thank you

**Comment by pgdouyon** [comment]
Niffler uses smart case sensitivity, meaning it's case-insensitive unless you type an uppercase letter.  It sounds like the bug you're running into has more to do with the fact that Niffler searches for the text literally by default but provides a few options for making the search more fuzzy.

So I think a query like `models*ticketcontroller` or `models ticket controller` (either a space or a `*`) would have matched the file.  `modelsticketcontroller` doesn't match because if the text is taken literally there would need to be a `\` in between "models" and "ticket"

Does that clear things up?

**Comment by baghayi** [comment]
yes, it kind of helps. thanks
